"""empty message

Revision ID: 0e1d61d09dcf
Revises: 
Create Date: 2026-09-25 06:33:20.694542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e1d61d09dcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Specialty',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Specialty', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Specialty_name'), ['name'], unique=True)

    op.create_table('Doctors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=200), nullable=False),
    sa.Column('last_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.Column('availabilty', sa.Boolean(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('licence_no', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['specialty_id'], ['Specialty.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('licence_no')
    )
    with op.batch_alter_table('Doctors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Doctors_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_Doctors_last_name'), ['last_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Doctors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Doctors_last_name'))
        batch_op.drop_index(batch_op.f('ix_Doctors_first_name'))

    op.drop_table('Doctors')
    with op.batch_alter_table('Specialty', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Specialty_name'))

    op.drop_table('Specialty')
    # ### end Alembic commands ###
